import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ameri Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        ></meta>
        <meta name="description" content="Landing page."></meta>
        <meta name="author" content="Esteban_Dev"></meta>
        <title>Ameri Barberia</title>
      </head>
      <body
        data-spy="scroll"
        data-target=".navbar"
        data-offset="40"
        id="home"
        className="bg-light dark:bg-dark"
      >
        {children}
      </body>
    </html>
  );
}
