import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        ></meta>
        <meta
          name="description"
          content="Start your development with JohnDoe landing page."
        ></meta>
        <meta name="author" content="Devcrud"></meta>
        <title>Ameri Barberia</title>
      </head>
      <body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">
        {children}
      </body>
    </html>
  );
}
